CREATE TABLE interviews (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    mode VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL,
    client_request_id VARCHAR(100) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    model_provider VARCHAR(40) NOT NULL,
    model_id VARCHAR(120) NOT NULL,
    resume_id UUID,
    question_bank_id UUID,
    title VARCHAR(255) NOT NULL,
    jd_text VARCHAR(1500),
    source_snapshot TEXT NOT NULL,
    question_plan TEXT NOT NULL DEFAULT '[]',
    main_question_target SMALLINT NOT NULL DEFAULT 6,
    current_main_index SMALLINT NOT NULL DEFAULT 0,
    current_followup_count SMALLINT NOT NULL DEFAULT 0,
    active_turn_id UUID,
    completion_reason VARCHAR(40),
    completion_request_id VARCHAR(100),
    transition_state VARCHAR(16) NOT NULL DEFAULT 'IDLE',
    transition_turn_id UUID,
    graph_thread_id VARCHAR(80) NOT NULL UNIQUE,
    model_data_consent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    state_version BIGINT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_interview_mode CHECK (mode IN ('COMPREHENSIVE', 'QUESTION_BANK')),
    CONSTRAINT ck_interview_status CHECK (status IN ('CREATED', 'PREPARING', 'RUNNING', 'COMPLETING', 'COMPLETE', 'START_FAILED')),
    CONSTRAINT ck_interview_sources CHECK (
        (mode = 'COMPREHENSIVE' AND resume_id IS NOT NULL AND question_bank_id IS NULL)
        OR (mode = 'QUESTION_BANK' AND resume_id IS NULL AND question_bank_id IS NOT NULL AND jd_text IS NULL)
    ),
    CONSTRAINT ck_interview_question_target CHECK (main_question_target BETWEEN 5 AND 8),
    CONSTRAINT ck_interview_current_index CHECK (current_main_index BETWEEN 0 AND main_question_target),
    CONSTRAINT ck_interview_followups CHECK (current_followup_count BETWEEN 0 AND 2),
    CONSTRAINT ck_interview_transition CHECK (transition_state IN ('IDLE', 'PENDING', 'PROCESSING')),
    CONSTRAINT uq_interview_owner_request UNIQUE (owner_id, client_request_id),
    CONSTRAINT uq_interview_id_owner UNIQUE (id, owner_id)
);

CREATE INDEX ix_interviews_owner_created ON interviews(owner_id, created_at DESC);
CREATE INDEX ix_interviews_owner_status ON interviews(owner_id, status, updated_at DESC);
CREATE INDEX ix_interviews_pending_transition ON interviews(transition_state, updated_at);

CREATE TABLE interview_turns (
    id UUID PRIMARY KEY,
    interview_id UUID NOT NULL,
    owner_id UUID NOT NULL,
    sequence_no INTEGER NOT NULL,
    turn_type VARCHAR(16) NOT NULL,
    main_question_index SMALLINT NOT NULL,
    followup_index SMALLINT,
    source_question_id VARCHAR(100),
    question TEXT NOT NULL,
    answer TEXT,
    status VARCHAR(16) NOT NULL DEFAULT 'ASKED',
    answer_request_id VARCHAR(100),
    asked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    answered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_turn_owner FOREIGN KEY (interview_id, owner_id)
        REFERENCES interviews(id, owner_id) ON DELETE CASCADE,
    CONSTRAINT ck_interview_turn_type CHECK (turn_type IN ('MAIN', 'FOLLOW_UP')),
    CONSTRAINT ck_interview_turn_index CHECK (main_question_index BETWEEN 1 AND 8),
    CONSTRAINT ck_interview_followup_index CHECK (
        (turn_type = 'MAIN' AND followup_index IS NULL)
        OR (turn_type = 'FOLLOW_UP' AND followup_index BETWEEN 1 AND 2)
    ),
    CONSTRAINT ck_interview_turn_status CHECK (status IN ('ASKED', 'ANSWERED', 'SKIPPED')),
    CONSTRAINT ck_interview_turn_answer CHECK (
        (status = 'ANSWERED' AND answer IS NOT NULL AND answered_at IS NOT NULL)
        OR (status <> 'ANSWERED' AND answer IS NULL AND answered_at IS NULL)
    ),
    CONSTRAINT uq_interview_turn_sequence UNIQUE (interview_id, sequence_no),
    CONSTRAINT uq_interview_turn_id_owner UNIQUE (id, owner_id)
);

CREATE UNIQUE INDEX uq_interview_turn_answer_request
    ON interview_turns(interview_id, answer_request_id);
CREATE INDEX ix_interview_turns_owner_interview ON interview_turns(owner_id, interview_id, sequence_no);

ALTER TABLE interviews
    ADD CONSTRAINT fk_interview_active_turn_owner
    FOREIGN KEY (active_turn_id) REFERENCES interview_turns(id) ON DELETE SET NULL;
ALTER TABLE interviews
    ADD CONSTRAINT fk_interview_transition_turn_owner
    FOREIGN KEY (transition_turn_id) REFERENCES interview_turns(id) ON DELETE SET NULL;

CREATE TABLE interview_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id UUID NOT NULL,
    owner_id UUID NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_event_owner FOREIGN KEY (interview_id, owner_id)
        REFERENCES interviews(id, owner_id) ON DELETE CASCADE
);

CREATE INDEX ix_interview_events_stream ON interview_events(interview_id, event_id);
